In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
response = requests.get('https://www.goodreads.com/list/show/6934.Science_Fiction_Books_by_Female_Authors')
doc = BeautifulSoup(response.text)

In [3]:
all_texts = doc.find_all('tr', itemtype='http://schema.org/Book')
rows = []
for text in all_texts:
    row={}
    row['Rank'] = text.find(class_='number').text.strip()
    row['Title'] = text.find(class_='bookTitle').text.strip()
    row['Author'] = text.find(class_='authorName').text.strip()
    row['Score'] = text.find('a', href='#').text.strip()
    row['Votes'] = text.find('a', href='#').find_next_sibling('a').text.strip()
    row['Rating'] = text.find(class_='minirating').text.strip()
    rows.append(row)
rows

df = pd.DataFrame(rows, columns=['Rank', 'Title', 'Author', 'Score', 'Votes', 'Rating'])
df.head()

,Rank,Title,Author,Score,Votes,Rating
0,1,The Handmaid's Tale,Margaret Atwood,"score: 30,733",314 people voted,"4.09 avg rating — 1,103,055 ratings"
1,2,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"score: 28,553",292 people voted,"4.33 avg rating — 5,742,381 ratings"
2,3,Frankenstein,Mary Wollstonecraft Shelley,"score: 21,909",224 people voted,"3.78 avg rating — 1,023,619 ratings"
3,4,"A Wrinkle in Time (Time Quintet, #1)",Madeleine L'Engle,"score: 18,720",196 people voted,"4.01 avg rating — 903,708 ratings"
4,5,The Left Hand of Darkness (Hainish Cycle #4),Ursula K. Le Guin,"score: 17,920",184 people voted,"4.06 avg rating — 98,822 ratings"

In [4]:
import re

In [5]:
df['Number_of_Ratings'] = df.Rating.str.extract("— (.*)")
df['Number_of_Ratings'] = df['Number_of_Ratings'].str.extract('(.*) ratings')
df.head()

,Rank,Title,Author,Score,Votes,Rating,Number_of_Ratings
0,1,The Handmaid's Tale,Margaret Atwood,"score: 30,733",314 people voted,"4.09 avg rating — 1,103,055 ratings","1,103,055"
1,2,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"score: 28,553",292 people voted,"4.33 avg rating — 5,742,381 ratings","5,742,381"
2,3,Frankenstein,Mary Wollstonecraft Shelley,"score: 21,909",224 people voted,"3.78 avg rating — 1,023,619 ratings","1,023,619"
3,4,"A Wrinkle in Time (Time Quintet, #1)",Madeleine L'Engle,"score: 18,720",196 people voted,"4.01 avg rating — 903,708 ratings","903,708"
4,5,The Left Hand of Darkness (Hainish Cycle #4),Ursula K. Le Guin,"score: 17,920",184 people voted,"4.06 avg rating — 98,822 ratings","98,822"

In [6]:
df['Number_of_Ratings'] = df.Number_of_Ratings.str.replace(',', '')
df.head()

,Rank,Title,Author,Score,Votes,Rating,Number_of_Ratings
0,1,The Handmaid's Tale,Margaret Atwood,"score: 30,733",314 people voted,"4.09 avg rating — 1,103,055 ratings",1103055
1,2,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"score: 28,553",292 people voted,"4.33 avg rating — 5,742,381 ratings",5742381
2,3,Frankenstein,Mary Wollstonecraft Shelley,"score: 21,909",224 people voted,"3.78 avg rating — 1,023,619 ratings",1023619
3,4,"A Wrinkle in Time (Time Quintet, #1)",Madeleine L'Engle,"score: 18,720",196 people voted,"4.01 avg rating — 903,708 ratings",903708
4,5,The Left Hand of Darkness (Hainish Cycle #4),Ursula K. Le Guin,"score: 17,920",184 people voted,"4.06 avg rating — 98,822 ratings",98822

In [7]:
df['Score'] = df['Score'].str.extract(r'score:(.*)')

In [8]:
df['Score'] = df['Score'].str.replace(',', '')
df.head()

,Rank,Title,Author,Score,Votes,Rating,Number_of_Ratings
0,1,The Handmaid's Tale,Margaret Atwood,30733,314 people voted,"4.09 avg rating — 1,103,055 ratings",1103055
1,2,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,28553,292 people voted,"4.33 avg rating — 5,742,381 ratings",5742381
2,3,Frankenstein,Mary Wollstonecraft Shelley,21909,224 people voted,"3.78 avg rating — 1,023,619 ratings",1023619
3,4,"A Wrinkle in Time (Time Quintet, #1)",Madeleine L'Engle,18720,196 people voted,"4.01 avg rating — 903,708 ratings",903708
4,5,The Left Hand of Darkness (Hainish Cycle #4),Ursula K. Le Guin,17920,184 people voted,"4.06 avg rating — 98,822 ratings",98822

In [9]:
df['Name'] = df.Title.str.replace(r'[(].*[)]', '')
df['Series'] = df.Title.str.extract("\((.*),")
df['Number in Series'] = df['Title'].str.extract(r", #([\d])")
df['Rating'] = df['Rating'].str.extract(r'(\d[.]\d\d)')
df.head()

,Rank,Title,Author,Score,Votes,Rating,Number_of_Ratings,Name,Series,Number in Series
0,1,The Handmaid's Tale,Margaret Atwood,30733,314 people voted,4.09,1103055,The Handmaid's Tale,NaN,NaN
1,2,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,28553,292 people voted,4.33,5742381,The Hunger Games,The Hunger Games,1
2,3,Frankenstein,Mary Wollstonecraft Shelley,21909,224 people voted,3.78,1023619,Frankenstein,NaN,NaN
3,4,"A Wrinkle in Time (Time Quintet, #1)",Madeleine L'Engle,18720,196 people voted,4.01,903708,A Wrinkle in Time,Time Quintet,1
4,5,The Left Hand of Darkness (Hainish Cycle #4),Ursula K. Le Guin,17920,184 people voted,4.06,98822,The Left Hand of Darkness,NaN,NaN

In [11]:
df = df.drop(columns='Title')

In [12]:
df.head()

,Rank,Author,Score,Votes,Rating,Number_of_Ratings,Name,Series,Number in Series
0,1,Margaret Atwood,30733,314 people voted,4.09,1103055,The Handmaid's Tale,NaN,NaN
1,2,Suzanne Collins,28553,292 people voted,4.33,5742381,The Hunger Games,The Hunger Games,1
2,3,Mary Wollstonecraft Shelley,21909,224 people voted,3.78,1023619,Frankenstein,NaN,NaN
3,4,Madeleine L'Engle,18720,196 people voted,4.01,903708,A Wrinkle in Time,Time Quintet,1
4,5,Ursula K. Le Guin,17920,184 people voted,4.06,98822,The Left Hand of Darkness,NaN,NaN

In [15]:
column_titles = ['Rank', 'Name', 'Author', 'Series', 'Number in Series', 'Score', 'Votes', 'Rating', 'Number_of_Ratings']
df.reindex(columns=column_titles)

,Rank,Name,Author,Series,Number in Series,Score,Votes,Rating,Number_of_Ratings
0,1,The Handmaid's Tale,Margaret Atwood,NaN,NaN,30733,314 people voted,4.09,1103055
1,2,The Hunger Games,Suzanne Collins,The Hunger Games,1,28553,292 people voted,4.33,5742381
2,3,Frankenstein,Mary Wollstonecraft Shelley,NaN,NaN,21909,224 people voted,3.78,1023619
3,4,A Wrinkle in Time,Madeleine L'Engle,Time Quintet,1,18720,196 people voted,4.01,903708
4,5,The Left Hand of Darkness,Ursula K. Le Guin,NaN,NaN,17920,184 people voted,4.06,98822
5,6,Divergent,Veronica Roth,Divergent,1,13326,138 people voted,4.21,2603197
6,7,Catching Fire,Suzanne Collins,The Hunger Games,2,12749,133 people voted,4.29,2200976
7,8,The Giver,Lois Lowry,The Giver,1,12399,129 people voted,4.12,1535394
8,9,Kindred,Octavia E. Butler,NaN,NaN,11070,116 people voted,4.23,72373
9,10,The Dispossessed,Ursula K. Le Guin,NaN,NaN,10731,112 people voted,4.21,71658
10,11,Oryx and Crake,Margaret Atwood,MaddAddam,1,10117,107 people voted,4.01,197835
11,12,Mockingjay,Suzanne Collins,The Hunger Games,3,9807,104 people voted,4.03,2072231
12,13,The Time Traveler's Wife,Audrey Niffenegger,NaN,NaN,9193,98 people voted,3.96,1446884
13,14,Doomsday Book,Connie Willis,Oxford Time Travel,1,8935,96 people voted,4.03,43257
14,15,The Lathe of Heaven,Ursula K. Le Guin,NaN,NaN,7775,84 people voted,4.11,44005
15,16,Ancillary Justice,Ann Leckie,NaN,NaN,7336,81 people voted,3.98,66225
16,17,Shards of Honour,Lois McMaster Bujold,Vorkosigan Saga,1,7017,75 people voted,4.11,25887
17,18,To Say Nothing of the Dog,Connie Willis,Oxford Time Travel,2,6890,74 people voted,4.13,29648
18,19,The Sparrow,Mary Doria Russell,The Sparrow,1,6873,72 people voted,4.17,52761
19,20,Dragonflight,Anne McCaffrey,Dragonriders of Pern,1,6802,74 people voted,4.10,116167
20,21,Parable of the Sower,Octavia E. Butler,Earthseed,1,6653,71 people voted,4.16,42267
21,22,The Warrior's Apprentice,Lois McMaster Bujold,Vorkosigan Saga,2,6087,65 people voted,4.29,20959
22,23,Barrayar,Lois McMaster Bujold,Vorkosigan Saga,7,5623,60 people voted,4.31,22112
23,24,The Host,Stephenie Meyer,The Host,1,5274,56 people voted,3.84,829057
24,25,Insurgent,Veronica Roth,Divergent,2,4899,54 people voted,4.05,1045927
25,26,Memory,Lois McMaster Bujold,Vorkosigan Saga,1,4682,51 people voted,4.45,13951
26,27,The Children of Men,P.D. James,NaN,NaN,4484,49 people voted,3.68,36108
27,28,Starshine: Aurora Rising Book One,G.S. Jennsen,Aurora Rhapsody,1,4394,45 people voted,3.91,2147
28,29,The Year of the Flood,Margaret Atwood,MaddAddam,2,4343,47 people voted,4.06,92243
29,30,Crystal Singer,Anne McCaffrey,Crystal Singer,1,4235,47 people voted,4.09,17775
...,...,...,...,...,...,...,...,...,...
70,71,Darkover Landfall,Marion Zimmer Bradley,NaN,NaN,1748,21 people voted,3.88,5952
71,72,Machinations,Hayley Stone,Machinations,1,1698,17 people voted,3.79,248
72,73,Vertigo,G.S. Jennsen,Aurora Rhapsody,2,1684,18 people voted,4.22,1042
73,74,CryoBurn,Lois McMaster Bujold,Vorkosigan Saga,1,1683,24 people voted,4.06,11943
74,75,Seed to Harvest,Octavia E. Butler,Patternmaster,1,1659,20 people voted,4.33,3946
75,76,The Wind's Twelve Quarters,Ursula K. Le Guin,NaN,NaN,1572,19 people voted,4.04,4042
76,77,Remnant Population,Elizabeth Moon,NaN,NaN,1547,20 people voted,4.06,3628
77,78,The Word for World is Forest,Ursula K. Le Guin,NaN,NaN,1510,20 people voted,3.95,12909
78,79,Grimspace,Ann Aguirre,Sirantha Jax,1,1497,17 people voted,3.73,12663
79,80,Ammonite,Nicola Griffith,NaN,NaN,1477,20 people voted,3.86,3716
80,81,Across the Universe,Beth Revis,Across the Universe,1,1435,16 people voted,3.77,107423
81,82,Inheritor,C.J. Cherryh,Foreigner,3,1392,18 people voted,4.19,3610
82,83,The V Girl,Mya Robarts,NaN,NaN,1380,15 people voted,4.02,7843
83,84,Delirium,Lauren Oliver,Delirium,1,1366,15 people voted,3.98,392313
84,85,Dreamsnake,Vonda N. McIntyre,NaN,NaN,1324,18 people voted,3.86,8407
85,86,Women of Wonder: Science-Fiction Stories by Wo...,Pamela Sargent,NaN,NaN,1297,16 people voted,4.00,272
86,87,All Systems Red,Martha Wells,The Murderbot Diaries,1,1296,14 people voted,4.15,35121
87,88,Trading in Danger,Elizabeth Moon,Vatta's War,1,1286,16 people voted,3.98,11164
88,89,Invader,C.J. Cherryh,Foreigner,2,1276,17 people voted,4.17,4058
89,89,Woman on the Edge of Time,Marge Piercy,NaN,NaN,1276,15 people voted,3.95,12600
90,91,China Mountain Zhang,Maureen F. McHugh,NaN,NaN,1253,18 people voted,3.94,3453
91,92,Stardoc,S.L. Viehl,Stardoc,1,1230,16 people voted,3.80,3632
92,93,MaddAddam,Margaret Atwood,MaddAddam,3,1212,13 people voted,4.00,52206
93,94,Valor's Choice,Tanya Huff,Confederation,1,1165,16 people voted,3.98,6900
94,95,Bellwether,Connie Willis,NaN,NaN,1142,13 people voted,3.93,10069
95,96,This Alien Shore,C.S. Friedman,NaN,NaN,1130,15 people voted,4.04,3262
96,97,Primary Inversion,Catherine Asaro,Saga of the Skolian Empire,1,1119,15 people voted,3.74,3686
97,98,Scarlet,Marissa Meyer,The Lunar Chronicles,2,1115,12 people voted,4.29,265354
98,99,Probability Moon,Nancy Kress,Probability,1,1107,15 people voted,3.61,1292
99,100,The House of the Scorpion,Nancy Farmer,Matteo Alacran,1,1083,12 people voted,4.10,72379

In [16]:
df = df.reindex(columns=column_titles)

In [17]:
df.head()

,Rank,Name,Author,Series,Number in Series,Score,Votes,Rating,Number_of_Ratings
0,1,The Handmaid's Tale,Margaret Atwood,NaN,NaN,30733,314 people voted,4.09,1103055
1,2,The Hunger Games,Suzanne Collins,The Hunger Games,1,28553,292 people voted,4.33,5742381
2,3,Frankenstein,Mary Wollstonecraft Shelley,NaN,NaN,21909,224 people voted,3.78,1023619
3,4,A Wrinkle in Time,Madeleine L'Engle,Time Quintet,1,18720,196 people voted,4.01,903708
4,5,The Left Hand of Darkness,Ursula K. Le Guin,NaN,NaN,17920,184 people voted,4.06,98822